package dev.oneuiproject.oneuiexample.fragment;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.drawable.Drawable;
import android.os.Bundle;
import android.util.TypedValue;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.SectionIndexer;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.sec.sesl.tester.R;
import dev.oneuiproject.oneuiexample.base.BaseFragment;

import java.util.ArrayList;
import java.util.List;

public class IconsFragment extends BaseFragment {
    /*todo search*/

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        RecyclerView iconListView = (RecyclerView) getView();
        iconListView.setLayoutManager(new LinearLayoutManager(mContext));
        iconListView.setAdapter(new ImageAdapter());
        iconListView.addItemDecoration(new ItemDecoration(mContext));
        iconListView.setItemAnimator(null);
        iconListView.seslSetFillBottomEnabled(true);
        iconListView.seslSetLastRoundedCorner(true);
        iconListView.seslSetFastScrollerEnabled(true);
        iconListView.seslSetGoToTopEnabled(true);
    }

    @Override
    public int getLayoutResId() {
        return R.layout.sample3_fragment_icons;
    }

    @Override
    public int getIconResId() {
        return R.drawable.drawer_page_icon_icons;
    }

    @Override
    public CharSequence getTitle() {
        return "Icons";
    }


    public class ImageAdapter extends RecyclerView.Adapter<ImageAdapter.ViewHolder>
            implements SectionIndexer {
        List<String> mSections = new ArrayList<>();
        List<Integer> mPositionForSection = new ArrayList<>();
        List<Integer> mSectionForPosition = new ArrayList<>();

        ImageAdapter() {
            for (int i = 0; i < iconIds.length; i++) {
                String letter = getResources().getResourceEntryName(iconIds[i])
                        .replace("ic_oui_", "").substring(0, 1).toUpperCase();

                if (Character.isDigit(letter.charAt(0))) {
                    letter = "#";
                }

                if (i == 0 || !mSections.get(mSections.size() - 1).equals(letter)) {
                    mSections.add(letter);
                    mPositionForSection.add(i);
                }
                mSectionForPosition.add(mSections.size() - 1);
            }
        }

        @Override
        public int getItemCount() {
            return iconIds.length;
        }

        @Override
        public long getItemId(final int position) {
            return position;
        }

        @NonNull
        @Override
        public ImageAdapter.ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
            LayoutInflater inflater = LayoutInflater.from(mContext);
            View view = inflater.inflate(R.layout.sample3_view_icon_listview_item, parent, false);
            return new ImageAdapter.ViewHolder(view);
        }

        @Override
        public void onBindViewHolder(ImageAdapter.ViewHolder holder, final int position) {
            holder.imageView.setImageResource(iconIds[position]);
            holder.textView.setText(getResources().getResourceEntryName(iconIds[position]));
        }

        @Override
        public Object[] getSections() {
            return mSections.toArray();
        }

        @Override
        public int getPositionForSection(int sectionIndex) {
            return mPositionForSection.get(sectionIndex);
        }

        @Override
        public int getSectionForPosition(int position) {
            return mSectionForPosition.get(position);
        }

        public class ViewHolder extends RecyclerView.ViewHolder {
            ImageView imageView;
            TextView textView;

            ViewHolder(View itemView) {
                super(itemView);
                imageView = itemView.findViewById(R.id.icon_list_item_icon);
                textView = itemView.findViewById(R.id.icon_list_item_text);
            }
        }
    }

    private class ItemDecoration extends RecyclerView.ItemDecoration {
        private final Drawable mDivider;

        public ItemDecoration(@NonNull Context context) {
            TypedValue outValue = new TypedValue();
            context.getTheme().resolveAttribute(R.attr.isLightTheme, outValue, true);

            mDivider = context.getDrawable(outValue.data == 0
                    ? R.drawable.sesl_list_divider_dark
                    : R.drawable.sesl_list_divider_light);
        }

        public void onDraw(@NonNull Canvas c, @NonNull RecyclerView parent,
                           @NonNull RecyclerView.State state) {
            super.onDraw(c, parent, state);

            for (int i = 0; i < parent.getChildCount(); i++) {
                View child = parent.getChildAt(i);
                final int top = child.getBottom()
                        + ((ViewGroup.MarginLayoutParams) child.getLayoutParams()).bottomMargin;
                final int bottom = mDivider.getIntrinsicHeight() + top;

                mDivider.setBounds(parent.getLeft(), top, parent.getRight(), bottom);
                mDivider.draw(c);
            }
        }
    }


    int[] iconIds = {
            R.drawable.ic_oui_360,
            R.drawable.ic_oui_ab_add,
            R.drawable.ic_oui_ab_app_info,
            R.drawable.ic_oui_ab_back,
            R.drawable.ic_oui_ab_call,
            R.drawable.ic_oui_ab_drawer,
            R.drawable.ic_oui_ab_favorites_off,
            R.drawable.ic_oui_ab_favorites_on,
            R.drawable.ic_oui_ab_more,
            R.drawable.ic_oui_ab_qr_code_scanner,
            R.drawable.ic_oui_ab_search,
            R.drawable.ic_oui_accessibility,
            R.drawable.ic_oui_accessibility_2,
            R.drawable.ic_oui_accounts_backup,
            R.drawable.ic_oui_action_run_a_quick_command,
            R.drawable.ic_oui_action_video_enhancer,
            R.drawable.ic_oui_add,
            R.drawable.ic_oui_add_filled,
            R.drawable.ic_oui_add_home,
            R.drawable.ic_oui_add_pdf,
            R.drawable.ic_oui_add_pdf_new,
            R.drawable.ic_oui_admob,
            R.drawable.ic_oui_advanced_call,
            R.drawable.ic_oui_advanced_call_outline,
            R.drawable.ic_oui_air_action,
            R.drawable.ic_oui_air_command,
            R.drawable.ic_oui_airplane_mode,
            R.drawable.ic_oui_alarm,
            R.drawable.ic_oui_alarm_2,
            R.drawable.ic_oui_alarm_dismissed,
            R.drawable.ic_oui_alarm_off,
            R.drawable.ic_oui_alarm_snooze,
            R.drawable.ic_oui_all_apps,
            R.drawable.ic_oui_always_get_key_notifications,
            R.drawable.ic_oui_alwaysask,
            R.drawable.ic_oui_alwys_on_display,
            R.drawable.ic_oui_amplify_sound,
            R.drawable.ic_oui_analyze_storage,
            R.drawable.ic_oui_android,
            R.drawable.ic_oui_animal,
            R.drawable.ic_oui_animals,
            R.drawable.ic_oui_apk,
            R.drawable.ic_oui_app_closed,
            R.drawable.ic_oui_app_open,
            R.drawable.ic_oui_app_opened,
            R.drawable.ic_oui_apps,
            R.drawable.ic_oui_apps_2,
            R.drawable.ic_oui_apps_outline,
            R.drawable.ic_oui_arrow_down,
            R.drawable.ic_oui_arrow_left,
            R.drawable.ic_oui_arrow_right,
            R.drawable.ic_oui_arrow_to_left,
            R.drawable.ic_oui_arrow_to_right,
            R.drawable.ic_oui_arrow_up,
            R.drawable.ic_oui_attach,
            R.drawable.ic_oui_audio,
            R.drawable.ic_oui_audio_filled,
            R.drawable.ic_oui_audio_noti,
            R.drawable.ic_oui_audio_noti_mute,
            R.drawable.ic_oui_audio_outline,
            R.drawable.ic_oui_audio_system,
            R.drawable.ic_oui_audio_system_mute,
            R.drawable.ic_oui_auto_sync,
            R.drawable.ic_oui_automation,
            R.drawable.ic_oui_back,
            R.drawable.ic_oui_back_and_forth,
            R.drawable.ic_oui_basic,
            R.drawable.ic_oui_basketball,
            R.drawable.ic_oui_battery,
            R.drawable.ic_oui_battery_icon,
            R.drawable.ic_oui_batterylevel,
            R.drawable.ic_oui_beans,
            R.drawable.ic_oui_beans_active_noise_canceling,
            R.drawable.ic_oui_beans_bixby_voice_wakeup,
            R.drawable.ic_oui_beans_equlizer,
            R.drawable.ic_oui_beans_gaming,
            R.drawable.ic_oui_beans_lock,
            R.drawable.ic_oui_beans_noti,
            R.drawable.ic_oui_beans_touchpad,
            R.drawable.ic_oui_bed,
            R.drawable.ic_oui_beep_once,
            R.drawable.ic_oui_beforebed,
            R.drawable.ic_oui_beforebed_easytutorials,
            R.drawable.ic_oui_benefit,
            R.drawable.ic_oui_bg_blur,
            R.drawable.ic_oui_biometric_type_face,
            R.drawable.ic_oui_biometric_type_fingerprint,
            R.drawable.ic_oui_bixby,
            R.drawable.ic_oui_bixby_voice,
            R.drawable.ic_oui_block,
            R.drawable.ic_oui_bluetooth,
            R.drawable.ic_oui_bluetooth_2,
            R.drawable.ic_oui_bluetooth_device,
            R.drawable.ic_oui_bluetooth_device_connect,
            R.drawable.ic_oui_bluetooth_device_disconnect,
            R.drawable.ic_oui_bluetooth_off,
            R.drawable.ic_oui_bookmark,
            R.drawable.ic_oui_bookmark_list,
            R.drawable.ic_oui_bookmark_list_outline,
            R.drawable.ic_oui_bookmark_outline,
            R.drawable.ic_oui_bracket,
            R.drawable.ic_oui_brightness,
            R.drawable.ic_oui_brightness_2,
            R.drawable.ic_oui_brightness_outline,
            R.drawable.ic_oui_brush,
            R.drawable.ic_oui_brush_outline,
            R.drawable.ic_oui_bud_ambient_sound,
            R.drawable.ic_oui_bud_equlizer,
            R.drawable.ic_oui_bud_gaming,
            R.drawable.ic_oui_bud_lock,
            R.drawable.ic_oui_bud_noti,
            R.drawable.ic_oui_bud_touchpad,
            R.drawable.ic_oui_buds,
            R.drawable.ic_oui_buds_live,
            R.drawable.ic_oui_buds_pro,
            R.drawable.ic_oui_budspro,
            R.drawable.ic_oui_budspro__lock_touchpad,
            R.drawable.ic_oui_budspro_active_noise_canceling,
            R.drawable.ic_oui_budspro_bixby_voice_wake_up,
            R.drawable.ic_oui_budspro_detect_conversation,
            R.drawable.ic_oui_budspro_equalizer_buds_,
            R.drawable.ic_oui_budspro_gaming,
            R.drawable.ic_oui_budspro_notifications,
            R.drawable.ic_oui_budspro_touch_and_hold_touchpad,
            R.drawable.ic_oui_calculation,
            R.drawable.ic_oui_calculation_root,
            R.drawable.ic_oui_calculation_root_3th,
            R.drawable.ic_oui_calendar,
            R.drawable.ic_oui_calendar_day,
            R.drawable.ic_oui_calendar_month,
            R.drawable.ic_oui_calendar_next_shedules,
            R.drawable.ic_oui_calendar_shedules_searched,
            R.drawable.ic_oui_calendar_task,
            R.drawable.ic_oui_calendar_week,
            R.drawable.ic_oui_calendar_year,
            R.drawable.ic_oui_call,
            R.drawable.ic_oui_call_log,
            R.drawable.ic_oui_call_text_other_device,
            R.drawable.ic_oui_camera,
            R.drawable.ic_oui_camera_flash_noti,
            R.drawable.ic_oui_camera_outline,
            R.drawable.ic_oui_car,
            R.drawable.ic_oui_cat,
            R.drawable.ic_oui_category_accessibility,
            R.drawable.ic_oui_category_accounts_backup,
            R.drawable.ic_oui_category_advanced_options,
            R.drawable.ic_oui_category_apps,
            R.drawable.ic_oui_category_attic,
            R.drawable.ic_oui_category_battery,
            R.drawable.ic_oui_category_beans,
            R.drawable.ic_oui_category_berry,
            R.drawable.ic_oui_category_bixby_voice,
            R.drawable.ic_oui_category_budspro,
            R.drawable.ic_oui_category_connections,
            R.drawable.ic_oui_category_display,
            R.drawable.ic_oui_category_effect,
            R.drawable.ic_oui_category_functions,
            R.drawable.ic_oui_category_galaxy_bud_plus,
            R.drawable.ic_oui_category_galaxy_watch,
            R.drawable.ic_oui_category_location,
            R.drawable.ic_oui_category_lockscreen,
            R.drawable.ic_oui_category_music,
            R.drawable.ic_oui_category_my_routines,
            R.drawable.ic_oui_category_notifications,
            R.drawable.ic_oui_category_security,
            R.drawable.ic_oui_category_smartthings,
            R.drawable.ic_oui_category_sounds,
            R.drawable.ic_oui_change_image,
            R.drawable.ic_oui_charging,
            R.drawable.ic_oui_checkbox_checked,
            R.drawable.ic_oui_checkbox_checked_outline,
            R.drawable.ic_oui_checkbox_unchecked,
            R.drawable.ic_oui_clear,
            R.drawable.ic_oui_clear_outline,
            R.drawable.ic_oui_clear_storage,
            R.drawable.ic_oui_clear_storage_outline,
            R.drawable.ic_oui_clipboard,
            R.drawable.ic_oui_close,
            R.drawable.ic_oui_color_adjustment,
            R.drawable.ic_oui_color_inversion,
            R.drawable.ic_oui_color_mix_hue,
            R.drawable.ic_oui_color_mix_luminance,
            R.drawable.ic_oui_color_mix_saturation,
            R.drawable.ic_oui_community,
            R.drawable.ic_oui_community_outline,
            R.drawable.ic_oui_compose,
            R.drawable.ic_oui_compose_edit,
            R.drawable.ic_oui_compose_outline,
            R.drawable.ic_oui_compressed,
            R.drawable.ic_oui_compressed_outline,
            R.drawable.ic_oui_confirm_before_next_action,
            R.drawable.ic_oui_connection,
            R.drawable.ic_oui_connections,
            R.drawable.ic_oui_contact,
            R.drawable.ic_oui_contact_outline,
            R.drawable.ic_oui_context,
            R.drawable.ic_oui_contrast,
            R.drawable.ic_oui_control_device,
            R.drawable.ic_oui_control_pause,
            R.drawable.ic_oui_control_pause_circle_filled,
            R.drawable.ic_oui_control_play,
            R.drawable.ic_oui_control_play_circle_filled,
            R.drawable.ic_oui_control_stop,
            R.drawable.ic_oui_copy,
            R.drawable.ic_oui_copy_outline,
            R.drawable.ic_oui_coupon,
            R.drawable.ic_oui_create_folder,
            R.drawable.ic_oui_creatures,
            R.drawable.ic_oui_creatures_outline,
            R.drawable.ic_oui_credit_card,
            R.drawable.ic_oui_credit_card_outline,
            R.drawable.ic_oui_crop_bottom_left,
            R.drawable.ic_oui_crop_bottom_right,
            R.drawable.ic_oui_crop_to_fit,
            R.drawable.ic_oui_crop_top_left,
            R.drawable.ic_oui_crop_top_right,
            R.drawable.ic_oui_crown,
            R.drawable.ic_oui_crown_outline,
            R.drawable.ic_oui_current_location,
            R.drawable.ic_oui_current_location_outline,
            R.drawable.ic_oui_cursor_select_handle_left,
            R.drawable.ic_oui_cursor_select_handle_middle,
            R.drawable.ic_oui_cursor_select_handle_right,
            R.drawable.ic_oui_cycling,
            R.drawable.ic_oui_daily_hunt,
            R.drawable.ic_oui_dark,
            R.drawable.ic_oui_dark_mode,
            R.drawable.ic_oui_decline,
            R.drawable.ic_oui_delete,
            R.drawable.ic_oui_delete_2,
            R.drawable.ic_oui_delete_outline,
            R.drawable.ic_oui_device,
            R.drawable.ic_oui_device_2,
            R.drawable.ic_oui_device_mobile_disconnect,
            R.drawable.ic_oui_device_outline,
            R.drawable.ic_oui_device_tablet_disconnect,
            R.drawable.ic_oui_dialing_keyboard,
            R.drawable.ic_oui_digital_wellbeing,
            R.drawable.ic_oui_digital_wellbeing_2,
            R.drawable.ic_oui_disable,
            R.drawable.ic_oui_discord,
            R.drawable.ic_oui_discord_outline,
            R.drawable.ic_oui_display,
            R.drawable.ic_oui_display_icon,
            R.drawable.ic_oui_disturb,
            R.drawable.ic_oui_do_not_disturb,
            R.drawable.ic_oui_document,
            R.drawable.ic_oui_document_outline,
            R.drawable.ic_oui_dog,
            R.drawable.ic_oui_dolby_atmos,
            R.drawable.ic_oui_download,
            R.drawable.ic_oui_download_circle_filled,
            R.drawable.ic_oui_download_circle_outline,
            R.drawable.ic_oui_drawer,
            R.drawable.ic_oui_driving,
            R.drawable.ic_oui_driving_condition,
            R.drawable.ic_oui_driving_easytutorials,
            R.drawable.ic_oui_dual_app,
            R.drawable.ic_oui_during_call,
            R.drawable.ic_oui_during_call_condition,
            R.drawable.ic_oui_during_call_profile,
            R.drawable.ic_oui_east,
            R.drawable.ic_oui_east_north_east,
            R.drawable.ic_oui_east_south_east,
            R.drawable.ic_oui_edge_light,
            R.drawable.ic_oui_edge_panels,
            R.drawable.ic_oui_edit,
            R.drawable.ic_oui_edit_outline,
            R.drawable.ic_oui_education,
            R.drawable.ic_oui_email,
            R.drawable.ic_oui_email_outline,
            R.drawable.ic_oui_email_read,
            R.drawable.ic_oui_email_sent,
            R.drawable.ic_oui_emergency,
            R.drawable.ic_oui_emoji,
            R.drawable.ic_oui_emoji_category_action,
            R.drawable.ic_oui_emoji_category_angry,
            R.drawable.ic_oui_emoji_category_animal,
            R.drawable.ic_oui_emoji_category_greeting,
            R.drawable.ic_oui_emoji_category_happy,
            R.drawable.ic_oui_emoji_category_love,
            R.drawable.ic_oui_emoji_category_sad,
            R.drawable.ic_oui_emoji_category_surprise,
            R.drawable.ic_oui_emoji_category_trouble,
            R.drawable.ic_oui_emoticon,
            R.drawable.ic_oui_enable,
            R.drawable.ic_oui_enable_outline,
            R.drawable.ic_oui_enhanced_processing,
            R.drawable.ic_oui_equalizer,
            R.drawable.ic_oui_equalizer_2,
            R.drawable.ic_oui_error,
            R.drawable.ic_oui_error_2,
            R.drawable.ic_oui_error_filled,
            R.drawable.ic_oui_error_outline,
            R.drawable.ic_oui_event,
            R.drawable.ic_oui_event_2,
            R.drawable.ic_oui_event_outline,
            R.drawable.ic_oui_expand,
            R.drawable.ic_oui_expand_horizontal,
            R.drawable.ic_oui_expand_vertical,
            R.drawable.ic_oui_explicit,
            R.drawable.ic_oui_exposure,
            R.drawable.ic_oui_eye_comfort_shield,
            R.drawable.ic_oui_eyes,
            R.drawable.ic_oui_fashion,
            R.drawable.ic_oui_fashion_outline,
            R.drawable.ic_oui_favorit_off,
            R.drawable.ic_oui_favorit_on,
            R.drawable.ic_oui_favorite,
            R.drawable.ic_oui_favorite_outline,
            R.drawable.ic_oui_file_type_adobe,
            R.drawable.ic_oui_file_type_amr,
            R.drawable.ic_oui_file_type_apk,
            R.drawable.ic_oui_file_type_audio,
            R.drawable.ic_oui_file_type_contact,
            R.drawable.ic_oui_file_type_eml,
            R.drawable.ic_oui_file_type_etc,
            R.drawable.ic_oui_file_type_excel,
            R.drawable.ic_oui_file_type_folder,
            R.drawable.ic_oui_file_type_ftp,
            R.drawable.ic_oui_file_type_gltf,
            R.drawable.ic_oui_file_type_hangul,
            R.drawable.ic_oui_file_type_html,
            R.drawable.ic_oui_file_type_image,
            R.drawable.ic_oui_file_type_memo,
            R.drawable.ic_oui_file_type_ppt,
            R.drawable.ic_oui_file_type_raw,
            R.drawable.ic_oui_file_type_rtf,
            R.drawable.ic_oui_file_type_scrapbook,
            R.drawable.ic_oui_file_type_sdoc,
            R.drawable.ic_oui_file_type_sftp,
            R.drawable.ic_oui_file_type_smb,
            R.drawable.ic_oui_file_type_snb,
            R.drawable.ic_oui_file_type_spd,
            R.drawable.ic_oui_file_type_story_album,
            R.drawable.ic_oui_file_type_svc,
            R.drawable.ic_oui_file_type_task_manager,
            R.drawable.ic_oui_file_type_txt,
            R.drawable.ic_oui_file_type_video,
            R.drawable.ic_oui_file_type_word,
            R.drawable.ic_oui_file_type_zip,
            R.drawable.ic_oui_filter_tab,
            R.drawable.ic_oui_fingerprint_error_move,
            R.drawable.ic_oui_fingerprint_error_timeout,
            R.drawable.ic_oui_fingerprint_error_wipe,
            R.drawable.ic_oui_fit_to_screen,
            R.drawable.ic_oui_flag,
            R.drawable.ic_oui_flag_outline,
            R.drawable.ic_oui_flashlight,
            R.drawable.ic_oui_flex_mode,
            R.drawable.ic_oui_flip_h,
            R.drawable.ic_oui_folder,
            R.drawable.ic_oui_folder_down,
            R.drawable.ic_oui_folder_home,
            R.drawable.ic_oui_folder_home_outline,
            R.drawable.ic_oui_folder_open,
            R.drawable.ic_oui_folder_outline,
            R.drawable.ic_oui_folder_root,
            R.drawable.ic_oui_folder_shrink,
            R.drawable.ic_oui_folder_to_left,
            R.drawable.ic_oui_folder_to_right,
            R.drawable.ic_oui_folding_status,
            R.drawable.ic_oui_folding_status_top,
            R.drawable.ic_oui_font_size,
            R.drawable.ic_oui_food,
            R.drawable.ic_oui_force_stop,
            R.drawable.ic_oui_force_stop_outline,
            R.drawable.ic_oui_functions,
            R.drawable.ic_oui_galaxy_bud_plus,
            R.drawable.ic_oui_galaxy_store,
            R.drawable.ic_oui_galaxy_store_outline,
            R.drawable.ic_oui_galaxy_watch,
            R.drawable.ic_oui_gallery_photo_search,
            R.drawable.ic_oui_game,
            R.drawable.ic_oui_game_2,
            R.drawable.ic_oui_game_detail,
            R.drawable.ic_oui_game_detail_outline,
            R.drawable.ic_oui_game_home_btn_lock,
            R.drawable.ic_oui_game_home_btn_navi_lock,
            R.drawable.ic_oui_game_launcher,
            R.drawable.ic_oui_game_outline,
            R.drawable.ic_oui_game_profile,
            R.drawable.ic_oui_game_tools,
            R.drawable.ic_oui_game_tools_outline,
            R.drawable.ic_oui_gif,
            R.drawable.ic_oui_gift,
            R.drawable.ic_oui_going_out,
            R.drawable.ic_oui_going_work,
            R.drawable.ic_oui_google,
            R.drawable.ic_oui_google_drive,
            R.drawable.ic_oui_google_duo,
            R.drawable.ic_oui_google_duo_outline,
            R.drawable.ic_oui_group,
            R.drawable.ic_oui_group_outline,
            R.drawable.ic_oui_group_sharing,
            R.drawable.ic_oui_hand_writing,
            R.drawable.ic_oui_hand_writing_change_style,
            R.drawable.ic_oui_hand_writing_convert_text,
            R.drawable.ic_oui_hand_writing_input,
            R.drawable.ic_oui_hart,
            R.drawable.ic_oui_heading_home,
            R.drawable.ic_oui_headphones,
            R.drawable.ic_oui_health,
            R.drawable.ic_oui_health_2,
            R.drawable.ic_oui_health_outline,
            R.drawable.ic_oui_hear,
            R.drawable.ic_oui_hearing_loud,
            R.drawable.ic_oui_hearing_none,
            R.drawable.ic_oui_hearing_normal,
            R.drawable.ic_oui_help,
            R.drawable.ic_oui_help_outline,
            R.drawable.ic_oui_hide_an_app,
            R.drawable.ic_oui_highlight,
            R.drawable.ic_oui_home,
            R.drawable.ic_oui_home_2,
            R.drawable.ic_oui_home_easytutorials,
            R.drawable.ic_oui_home_outline,
            R.drawable.ic_oui_image,
            R.drawable.ic_oui_image_outline,
            R.drawable.ic_oui_image_visual,
            R.drawable.ic_oui_import,
            R.drawable.ic_oui_inbox,
            R.drawable.ic_oui_inbox_outline,
            R.drawable.ic_oui_info,
            R.drawable.ic_oui_info_outline,
            R.drawable.ic_oui_internet_website,
            R.drawable.ic_oui_kaomoji,
            R.drawable.ic_oui_keyboard,
            R.drawable.ic_oui_keyboard_arrow_down,
            R.drawable.ic_oui_keyboard_arrow_left,
            R.drawable.ic_oui_keyboard_arrow_right,
            R.drawable.ic_oui_keyboard_arrow_up,
            R.drawable.ic_oui_keyboard_btn_delete,
            R.drawable.ic_oui_keyboard_btn_enter,
            R.drawable.ic_oui_keyboard_btn_shift,
            R.drawable.ic_oui_keyboard_btn_shift_outline,
            R.drawable.ic_oui_keyboard_btn_space,
            R.drawable.ic_oui_keyboard_fixed,
            R.drawable.ic_oui_keyboard_floating,
            R.drawable.ic_oui_keyboard_japanese_email,
            R.drawable.ic_oui_keyboard_japanese_email02,
            R.drawable.ic_oui_keyboard_japanese_small,
            R.drawable.ic_oui_keyboard_japanese_url,
            R.drawable.ic_oui_keyboard_japanese_url_jp,
            R.drawable.ic_oui_keyboard_language_en_nomal,
            R.drawable.ic_oui_keyboard_language_kr_nomal,
            R.drawable.ic_oui_keyboard_language_nomal,
            R.drawable.ic_oui_keyboard_mode,
            R.drawable.ic_oui_keyboard_mode_floating,
            R.drawable.ic_oui_keyboard_mode_one_hand,
            R.drawable.ic_oui_keyboard_mode_split,
            R.drawable.ic_oui_keyboard_mode_standard,
            R.drawable.ic_oui_keyboard_numeric_thai,
            R.drawable.ic_oui_keyboard_numeric_vietnamese,
            R.drawable.ic_oui_keyboard_sound,
            R.drawable.ic_oui_keyboard_split,
            R.drawable.ic_oui_keyboard_standard,
            R.drawable.ic_oui_keyboard_vibration,
            R.drawable.ic_oui_keyboard_zwnj,
            R.drawable.ic_oui_kids,
            R.drawable.ic_oui_knox,
            R.drawable.ic_oui_labs,
            R.drawable.ic_oui_labs_2,
            R.drawable.ic_oui_labs_outline,
            R.drawable.ic_oui_lasso,
            R.drawable.ic_oui_lasso_add,
            R.drawable.ic_oui_lasso_auto,
            R.drawable.ic_oui_lasso_remove,
            R.drawable.ic_oui_leave,
            R.drawable.ic_oui_letters,
            R.drawable.ic_oui_lightbalance,
            R.drawable.ic_oui_lightning,
            R.drawable.ic_oui_lightning_outline,
            R.drawable.ic_oui_like,
            R.drawable.ic_oui_link_to_windows,
            R.drawable.ic_oui_list,
            R.drawable.ic_oui_list_add,
            R.drawable.ic_oui_list_audio,
            R.drawable.ic_oui_list_extended,
            R.drawable.ic_oui_list_filter,
            R.drawable.ic_oui_list_grid,
            R.drawable.ic_oui_list_search,
            R.drawable.ic_oui_list_sim_1,
            R.drawable.ic_oui_list_sim_2,
            R.drawable.ic_oui_list_sim_3,
            R.drawable.ic_oui_list_sim_call,
            R.drawable.ic_oui_list_sim_heart,
            R.drawable.ic_oui_list_sim_home,
            R.drawable.ic_oui_list_sim_internet,
            R.drawable.ic_oui_list_sim_mms,
            R.drawable.ic_oui_list_sim_office,
            R.drawable.ic_oui_list_sim_sms,
            R.drawable.ic_oui_list_sim_travel,
            R.drawable.ic_oui_list_sim_trip,
            R.drawable.ic_oui_list_sort,
            R.drawable.ic_oui_list_view_by,
            R.drawable.ic_oui_listen,
            R.drawable.ic_oui_listen_outline,
            R.drawable.ic_oui_live_caption,
            R.drawable.ic_oui_location,
            R.drawable.ic_oui_location_2,
            R.drawable.ic_oui_location_off,
            R.drawable.ic_oui_location_outline,
            R.drawable.ic_oui_lock,
            R.drawable.ic_oui_lock_2,
            R.drawable.ic_oui_lock_outline,
            R.drawable.ic_oui_lockdown_the_phone,
            R.drawable.ic_oui_lockscreen,
            R.drawable.ic_oui_lockscreen_wallpaper,
            R.drawable.ic_oui_long_legs,
            R.drawable.ic_oui_magnifying_glass_01,
            R.drawable.ic_oui_magnifying_glass_02,
            R.drawable.ic_oui_magnifying_glass_03,
            R.drawable.ic_oui_makeup,
            R.drawable.ic_oui_manage_storage,
            R.drawable.ic_oui_manage_storage_outline,
            R.drawable.ic_oui_media_volume,
            R.drawable.ic_oui_meeting,
            R.drawable.ic_oui_memo,
            R.drawable.ic_oui_memo_outline,
            R.drawable.ic_oui_memo_scanner,
            R.drawable.ic_oui_memo_scanner_outline,
            R.drawable.ic_oui_message,
            R.drawable.ic_oui_message_2,
            R.drawable.ic_oui_message_all_read,
            R.drawable.ic_oui_message_bot,
            R.drawable.ic_oui_message_chat,
            R.drawable.ic_oui_message_markasread,
            R.drawable.ic_oui_message_markasread_outline,
            R.drawable.ic_oui_message_note,
            R.drawable.ic_oui_message_outline,
            R.drawable.ic_oui_message_search,
            R.drawable.ic_oui_message_send,
            R.drawable.ic_oui_minimize,
            R.drawable.ic_oui_minus,
            R.drawable.ic_oui_mms,
            R.drawable.ic_oui_mobile_data,
            R.drawable.ic_oui_mobile_hotspot,
            R.drawable.ic_oui_mono_audio,
            R.drawable.ic_oui_more,
            R.drawable.ic_oui_morning,
            R.drawable.ic_oui_morning_easytutorials,
            R.drawable.ic_oui_motion,
            R.drawable.ic_oui_move,
            R.drawable.ic_oui_move_outline,
            R.drawable.ic_oui_movie,
            R.drawable.ic_oui_multi_window_tray,
            R.drawable.ic_oui_music,
            R.drawable.ic_oui_music_2,
            R.drawable.ic_oui_music_icon,
            R.drawable.ic_oui_music_melon,
            R.drawable.ic_oui_music_outline,
            R.drawable.ic_oui_music_share,
            R.drawable.ic_oui_mute,
            R.drawable.ic_oui_mute_all_sound,
            R.drawable.ic_oui_my_routines,
            R.drawable.ic_oui_myrouitnes_card,
            R.drawable.ic_oui_nature,
            R.drawable.ic_oui_navigate,
            R.drawable.ic_oui_navigationbar,
            R.drawable.ic_oui_nearby_devices,
            R.drawable.ic_oui_network_storage,
            R.drawable.ic_oui_network_storage_manage,
            R.drawable.ic_oui_network_storage_manage_outline,
            R.drawable.ic_oui_network_storage_outline,
            R.drawable.ic_oui_news,
            R.drawable.ic_oui_news_outline,
            R.drawable.ic_oui_nfc,
            R.drawable.ic_oui_nfc_2,
            R.drawable.ic_oui_nfc_tagged,
            R.drawable.ic_oui_night_life,
            R.drawable.ic_oui_no_network,
            R.drawable.ic_oui_north,
            R.drawable.ic_oui_north_east,
            R.drawable.ic_oui_north_north_east,
            R.drawable.ic_oui_north_north_west,
            R.drawable.ic_oui_north_west,
            R.drawable.ic_oui_notes,
            R.drawable.ic_oui_notes_new,
            R.drawable.ic_oui_notice,
            R.drawable.ic_oui_notice_outline,
            R.drawable.ic_oui_notification_received_with_keyword,
            R.drawable.ic_oui_notification_with_keyword,
            R.drawable.ic_oui_notifications,
            R.drawable.ic_oui_nowind,
            R.drawable.ic_oui_object,
            R.drawable.ic_oui_object_eraser,
            R.drawable.ic_oui_one_drive,
            R.drawable.ic_oui_open,
            R.drawable.ic_oui_open_app,
            R.drawable.ic_oui_open_split_view,
            R.drawable.ic_oui_outbox,
            R.drawable.ic_oui_page_lock,
            R.drawable.ic_oui_page_lock_outline,
            R.drawable.ic_oui_page_settings,
            R.drawable.ic_oui_page_template,
            R.drawable.ic_oui_page_theme,
            R.drawable.ic_oui_page_unlock,
            R.drawable.ic_oui_page_unlock_outline,
            R.drawable.ic_oui_palette,
            R.drawable.ic_oui_parental_control,
            R.drawable.ic_oui_parking,
            R.drawable.ic_oui_password_hide,
            R.drawable.ic_oui_password_show,
            R.drawable.ic_oui_pen,
            R.drawable.ic_oui_pen_calligraphy,
            R.drawable.ic_oui_pen_calligraphy_brush,
            R.drawable.ic_oui_pen_drawing,
            R.drawable.ic_oui_pen_eraser,
            R.drawable.ic_oui_pen_eraser_outline,
            R.drawable.ic_oui_pen_fountain,
            R.drawable.ic_oui_pen_marker,
            R.drawable.ic_oui_pen_marker_round,
            R.drawable.ic_oui_pen_mode,
            R.drawable.ic_oui_pen_mosaic,
            R.drawable.ic_oui_pencil,
            R.drawable.ic_oui_period_time,
            R.drawable.ic_oui_perspective_horizontal,
            R.drawable.ic_oui_perspective_vertical,
            R.drawable.ic_oui_pets,
            R.drawable.ic_oui_phone,
            R.drawable.ic_oui_phone_call_someone,
            R.drawable.ic_oui_phone_outline,
            R.drawable.ic_oui_pin,
            R.drawable.ic_oui_pin_off,
            R.drawable.ic_oui_pin_outline,
            R.drawable.ic_oui_place,
            R.drawable.ic_oui_planner,
            R.drawable.ic_oui_play_music,
            R.drawable.ic_oui_playlist,
            R.drawable.ic_oui_plug_in_download,
            R.drawable.ic_oui_plug_in_manager,
            R.drawable.ic_oui_plug_in_manager_outline,
            R.drawable.ic_oui_pollen,
            R.drawable.ic_oui_popup_player,
            R.drawable.ic_oui_post,
            R.drawable.ic_oui_power,
            R.drawable.ic_oui_privacy,
            R.drawable.ic_oui_private_share,
            R.drawable.ic_oui_prompt_from_menu,
            R.drawable.ic_oui_puzzle,
            R.drawable.ic_oui_qr_code,
            R.drawable.ic_oui_qr_code_scanner,
            R.drawable.ic_oui_quick_command,
            R.drawable.ic_oui_ratio,
            R.drawable.ic_oui_ratio_1_1,
            R.drawable.ic_oui_ratio_1_1_2nd,
            R.drawable.ic_oui_ratio_2nd,
            R.drawable.ic_oui_ratio_3_4,
            R.drawable.ic_oui_ratio_3_4_2nd,
            R.drawable.ic_oui_ratio_4_3,
            R.drawable.ic_oui_ratio_4_3_2nd,
            R.drawable.ic_oui_ratio_9_16,
            R.drawable.ic_oui_ratio_9_16_2nd,
            R.drawable.ic_oui_ratio_16_9,
            R.drawable.ic_oui_ratio_16_9_2nd,
            R.drawable.ic_oui_ratio_free,
            R.drawable.ic_oui_ratio_free_2nd,
            R.drawable.ic_oui_ratio_full,
            R.drawable.ic_oui_ratio_full_2nd,
            R.drawable.ic_oui_ratio_landscape_off,
            R.drawable.ic_oui_ratio_landscape_on,
            R.drawable.ic_oui_ratio_portrait_off,
            R.drawable.ic_oui_ratio_portrait_on,
            R.drawable.ic_oui_read,
            R.drawable.ic_oui_read_book,
            R.drawable.ic_oui_reading_mode,
            R.drawable.ic_oui_receipt,
            R.drawable.ic_oui_receiving_message_from_keywords,
            R.drawable.ic_oui_receiving_message_from_someone,
            R.drawable.ic_oui_receiving_message_including_some_keywords,
            R.drawable.ic_oui_recent,
            R.drawable.ic_oui_recent_outline,
            R.drawable.ic_oui_recent_view,
            R.drawable.ic_oui_recent_view_outline,
            R.drawable.ic_oui_record,
            R.drawable.ic_oui_rectify,
            R.drawable.ic_oui_redo,
            R.drawable.ic_oui_refresh,
            R.drawable.ic_oui_refresh_rate,
            R.drawable.ic_oui_reject_call,
            R.drawable.ic_oui_reminder,
            R.drawable.ic_oui_reminder_off,
            R.drawable.ic_oui_reminder_off_outline,
            R.drawable.ic_oui_reminder_outline,
            R.drawable.ic_oui_remove,
            R.drawable.ic_oui_remove_2,
            R.drawable.ic_oui_remove_outline,
            R.drawable.ic_oui_reorder,
            R.drawable.ic_oui_repeat,
            R.drawable.ic_oui_repeat_1,
            R.drawable.ic_oui_repeat_all,
            R.drawable.ic_oui_repeat_off,
            R.drawable.ic_oui_reply,
            R.drawable.ic_oui_reply_all,
            R.drawable.ic_oui_report,
            R.drawable.ic_oui_resize,
            R.drawable.ic_oui_restart,
            R.drawable.ic_oui_restaurants,
            R.drawable.ic_oui_revert,
            R.drawable.ic_oui_reverted,
            R.drawable.ic_oui_robot,
            R.drawable.ic_oui_rotate,
            R.drawable.ic_oui_rotate_2,
            R.drawable.ic_oui_rotate_outline,
            R.drawable.ic_oui_routines,
            R.drawable.ic_oui_running,
            R.drawable.ic_oui_samsung_account,
            R.drawable.ic_oui_samsung_cloud_drive,
            R.drawable.ic_oui_samsung_dex,
            R.drawable.ic_oui_samsung_free,
            R.drawable.ic_oui_samsung_health,
            R.drawable.ic_oui_samsung_one,
            R.drawable.ic_oui_saturation,
            R.drawable.ic_oui_save,
            R.drawable.ic_oui_save_battery,
            R.drawable.ic_oui_save_copy,
            R.drawable.ic_oui_save_outline,
            R.drawable.ic_oui_school,
            R.drawable.ic_oui_screen_capture,
            R.drawable.ic_oui_screen_flash_noti,
            R.drawable.ic_oui_screen_off,
            R.drawable.ic_oui_screen_orientation,
            R.drawable.ic_oui_screen_resolution,
            R.drawable.ic_oui_screen_shortcuts,
            R.drawable.ic_oui_screen_timeout,
            R.drawable.ic_oui_screen_zoom,
            R.drawable.ic_oui_screenshot,
            R.drawable.ic_oui_script,
            R.drawable.ic_oui_sd_card,
            R.drawable.ic_oui_sd_card_outline,
            R.drawable.ic_oui_search,
            R.drawable.ic_oui_secure_wifi,
            R.drawable.ic_oui_security,
            R.drawable.ic_oui_security_2,
            R.drawable.ic_oui_security_outline,
            R.drawable.ic_oui_selected,
            R.drawable.ic_oui_selection_lasso,
            R.drawable.ic_oui_selection_rectangle,
            R.drawable.ic_oui_send,
            R.drawable.ic_oui_separate,
            R.drawable.ic_oui_settings,
            R.drawable.ic_oui_settings_outline,
            R.drawable.ic_oui_shadow,
            R.drawable.ic_oui_shape,
            R.drawable.ic_oui_share,
            R.drawable.ic_oui_share_outline,
            R.drawable.ic_oui_shopping,
            R.drawable.ic_oui_show_action_list,
            R.drawable.ic_oui_show_custom_notification,
            R.drawable.ic_oui_shuffle,
            R.drawable.ic_oui_shuffle_off,
            R.drawable.ic_oui_sim,
            R.drawable.ic_oui_slim_face,
            R.drawable.ic_oui_smart_popup,
            R.drawable.ic_oui_smart_view,
            R.drawable.ic_oui_smartthings,
            R.drawable.ic_oui_smartthings_2,
            R.drawable.ic_oui_smile_emoticon,
            R.drawable.ic_oui_smoothness,
            R.drawable.ic_oui_sound,
            R.drawable.ic_oui_sound_2,
            R.drawable.ic_oui_sound_3,
            R.drawable.ic_oui_sound_balance,
            R.drawable.ic_oui_sound_mute,
            R.drawable.ic_oui_sound_mute_2,
            R.drawable.ic_oui_sound_mute_outline,
            R.drawable.ic_oui_sound_outline,
            R.drawable.ic_oui_sound_vibrate,
            R.drawable.ic_oui_sound_vibrate_2,
            R.drawable.ic_oui_sound_vibrate_outline,
            R.drawable.ic_oui_soundmode,
            R.drawable.ic_oui_sounds,
            R.drawable.ic_oui_south,
            R.drawable.ic_oui_south_east,
            R.drawable.ic_oui_south_south_east,
            R.drawable.ic_oui_south_south_west,
            R.drawable.ic_oui_south_west,
            R.drawable.ic_oui_speed,
            R.drawable.ic_oui_speed_player,
            R.drawable.ic_oui_spoid,
            R.drawable.ic_oui_spoid_outline,
            R.drawable.ic_oui_sports,
            R.drawable.ic_oui_spot_remover,
            R.drawable.ic_oui_spotify,
            R.drawable.ic_oui_spotify_2,
            R.drawable.ic_oui_squircle,
            R.drawable.ic_oui_star,
            R.drawable.ic_oui_star_2,
            R.drawable.ic_oui_star_outline,
            R.drawable.ic_oui_start,
            R.drawable.ic_oui_start_a_stopwatch,
            R.drawable.ic_oui_sticker,
            R.drawable.ic_oui_sticker_outline,
            R.drawable.ic_oui_streaming,
            R.drawable.ic_oui_strech,
            R.drawable.ic_oui_super_slow,
            R.drawable.ic_oui_support,
            R.drawable.ic_oui_support_outline,
            R.drawable.ic_oui_symbol_dollar,
            R.drawable.ic_oui_symbols,
            R.drawable.ic_oui_sync,
            R.drawable.ic_oui_sysbar_back,
            R.drawable.ic_oui_sysbar_back_ime,
            R.drawable.ic_oui_sysbar_docked,
            R.drawable.ic_oui_sysbar_home,
            R.drawable.ic_oui_sysbar_recent,
            R.drawable.ic_oui_system_alert_window,
            R.drawable.ic_oui_taboola,
            R.drawable.ic_oui_tag,
            R.drawable.ic_oui_temperature,
            R.drawable.ic_oui_text,
            R.drawable.ic_oui_text_align,
            R.drawable.ic_oui_text_align_center,
            R.drawable.ic_oui_text_align_left,
            R.drawable.ic_oui_text_align_right,
            R.drawable.ic_oui_text_bold,
            R.drawable.ic_oui_text_check_off,
            R.drawable.ic_oui_text_check_on,
            R.drawable.ic_oui_text_checkbox,
            R.drawable.ic_oui_text_direct_writing,
            R.drawable.ic_oui_text_dot,
            R.drawable.ic_oui_text_font_bg_color,
            R.drawable.ic_oui_text_font_color,
            R.drawable.ic_oui_text_indent,
            R.drawable.ic_oui_text_italic,
            R.drawable.ic_oui_text_numbering,
            R.drawable.ic_oui_text_outdent,
            R.drawable.ic_oui_text_setting,
            R.drawable.ic_oui_text_strikethrough,
            R.drawable.ic_oui_text_style_bold,
            R.drawable.ic_oui_text_style_default,
            R.drawable.ic_oui_text_style_glow,
            R.drawable.ic_oui_text_style_italic,
            R.drawable.ic_oui_text_style_round,
            R.drawable.ic_oui_text_style_stroke,
            R.drawable.ic_oui_text_style_thin,
            R.drawable.ic_oui_text_style_underline,
            R.drawable.ic_oui_text_underline,
            R.drawable.ic_oui_theme,
            R.drawable.ic_oui_ticket,
            R.drawable.ic_oui_time,
            R.drawable.ic_oui_time_profile,
            R.drawable.ic_oui_timer,
            R.drawable.ic_oui_timer_2,
            R.drawable.ic_oui_tint,
            R.drawable.ic_oui_tips,
            R.drawable.ic_oui_tips_2,
            R.drawable.ic_oui_tips_outline,
            R.drawable.ic_oui_tone_tab,
            R.drawable.ic_oui_tool,
            R.drawable.ic_oui_tool_outline,
            R.drawable.ic_oui_transform,
            R.drawable.ic_oui_translate,
            R.drawable.ic_oui_transliteration,
            R.drawable.ic_oui_travel,
            R.drawable.ic_oui_traveling,
            R.drawable.ic_oui_trim,
            R.drawable.ic_oui_turn_off_alarms,
            R.drawable.ic_oui_turn_on_alarms,
            R.drawable.ic_oui_ultra_data_saving,
            R.drawable.ic_oui_unbind,
            R.drawable.ic_oui_undo,
            R.drawable.ic_oui_unlock,
            R.drawable.ic_oui_unlock_outline,
            R.drawable.ic_oui_unlock_phone,
            R.drawable.ic_oui_upday,
            R.drawable.ic_oui_upload,
            R.drawable.ic_oui_usb,
            R.drawable.ic_oui_usb_outline,
            R.drawable.ic_oui_utc,
            R.drawable.ic_oui_vibrate,
            R.drawable.ic_oui_video,
            R.drawable.ic_oui_video_call,
            R.drawable.ic_oui_video_call_non_capable,
            R.drawable.ic_oui_video_call_non_capable_outline,
            R.drawable.ic_oui_video_call_outline,
            R.drawable.ic_oui_video_capture,
            R.drawable.ic_oui_video_enhancer,
            R.drawable.ic_oui_video_outline,
            R.drawable.ic_oui_vip,
            R.drawable.ic_oui_vision,
            R.drawable.ic_oui_voice,
            R.drawable.ic_oui_voice_wakeup,
            R.drawable.ic_oui_volume,
            R.drawable.ic_oui_volume_down,
            R.drawable.ic_oui_volume_up,
            R.drawable.ic_oui_vpn_connect,
            R.drawable.ic_oui_vpn_disconnect,
            R.drawable.ic_oui_wake_up_time,
            R.drawable.ic_oui_wallpaper,
            R.drawable.ic_oui_wallpaper_outline,
            R.drawable.ic_oui_watch,
            R.drawable.ic_oui_watch_theatermode,
            R.drawable.ic_oui_wave,
            R.drawable.ic_oui_weather,
            R.drawable.ic_oui_weather_clear,
            R.drawable.ic_oui_weather_cloudy,
            R.drawable.ic_oui_weather_cold,
            R.drawable.ic_oui_weather_day,
            R.drawable.ic_oui_weather_flurries,
            R.drawable.ic_oui_weather_fog,
            R.drawable.ic_oui_weather_hail,
            R.drawable.ic_oui_weather_heavy_rain,
            R.drawable.ic_oui_weather_hot,
            R.drawable.ic_oui_weather_hurricane,
            R.drawable.ic_oui_weather_ice,
            R.drawable.ic_oui_weather_loading,
            R.drawable.ic_oui_weather_mostly_clear,
            R.drawable.ic_oui_weather_night,
            R.drawable.ic_oui_weather_oobe,
            R.drawable.ic_oui_weather_partly_sunny,
            R.drawable.ic_oui_weather_partly_sunny_with_flurries,
            R.drawable.ic_oui_weather_partly_sunny_with_shower,
            R.drawable.ic_oui_weather_partly_sunny_with_thunder_shower,
            R.drawable.ic_oui_weather_rain,
            R.drawable.ic_oui_weather_rain_and_snow_mixed,
            R.drawable.ic_oui_weather_sand_storm,
            R.drawable.ic_oui_weather_shower,
            R.drawable.ic_oui_weather_snow,
            R.drawable.ic_oui_weather_sunny,
            R.drawable.ic_oui_weather_thunder_storm,
            R.drawable.ic_oui_weather_wake_up,
            R.drawable.ic_oui_weather_windy,
            R.drawable.ic_oui_web_search,
            R.drawable.ic_oui_website,
            R.drawable.ic_oui_west,
            R.drawable.ic_oui_west_north_west,
            R.drawable.ic_oui_west_south_west,
            R.drawable.ic_oui_whirlwind,
            R.drawable.ic_oui_widget,
            R.drawable.ic_oui_widget_outline,
            R.drawable.ic_oui_wifi,
            R.drawable.ic_oui_wifi_2,
            R.drawable.ic_oui_wifi_3,
            R.drawable.ic_oui_wifi_call,
            R.drawable.ic_oui_wifi_call_outline,
            R.drawable.ic_oui_wifi_call_spr,
            R.drawable.ic_oui_wifi_call_spr_outline,
            R.drawable.ic_oui_wifi_call_vzw,
            R.drawable.ic_oui_wifi_call_vzw_outline,
            R.drawable.ic_oui_wifi_network,
            R.drawable.ic_oui_wifi_strength_1,
            R.drawable.ic_oui_wifi_strength_2,
            R.drawable.ic_oui_wifi_strength_3,
            R.drawable.ic_oui_wifi_strength_4,
            R.drawable.ic_oui_wifi_video_call_non_capable,
            R.drawable.ic_oui_wifi_video_call_non_capable_outline,
            R.drawable.ic_oui_wifi_video_call_tmo_global,
            R.drawable.ic_oui_wifi_video_call_vzw,
            R.drawable.ic_oui_wifi_video_call_vzw_outline,
            R.drawable.ic_oui_work,
            R.drawable.ic_oui_work_2,
            R.drawable.ic_oui_work_private,
            R.drawable.ic_oui_work_profile,
            R.drawable.ic_oui_work_profile_outline,
            R.drawable.ic_oui_workout
    };
}
